workflows:
  flutter-ios-simulator:
    name: Flutter iOS Simulator
    environment:
      flutter: 3.35.4  # Update this to match the suggested version
      xcode: 16.2
    scripts:
      - flutter build ios --simulator --flavor staging
    artifacts:
      - build/ios/iphonesimulator/Runner.app
